### ISSUE TITLE
Remove AppInsights reference from the HostingStartup package

### ISSUE THREAD

**Issue by glennc** [aspnet/AzureIntegration#108]
Explicitly depending on the app insights SDK from this package pins people using lightup to get new versions the same way. Because apps versions of things always win customers need to redeploy their app with a new version of the App Insights SDK if they want new features. Even though the point of this was that they never had to worry about app insights in their app.

It means we will need use things like Assembly.Load and make sure that the SDK still goes into the store even though it isn't explicitly referenced by this package.

**Comment by glennc** [comment]
@anurse

**Comment by muratg** [comment]
@Eilon This is a patch candidate. @pakrym will be thinking about the implications and how to achieve this in addition to the scenarios we'd have to test.

**Comment by pakrym** [comment]
We are looking on two ways of accomplishing this task:
1. Adding `HostingStartup.Implementation` assembly, moving all current `HostingStartup` code to it  and calling into it using `Assembly.Load` and reflection from current `HostingStartup` that stays in `MetaPackage`. This 

2. Removing `HostingStartup` from `MetaPackage` and keeping everything else as is.

No matter what we do we lose an ability to test latest `HostingStartup` in VS by referencing latest metapackage because it won't contain implementation and additional deps would be injected for `c:\Program Files\dotnet\additionalDeps\Microsoft.AspNetCore.ApplicationInsights.HostingStartup\shared\Microsoft.NETCore.App\2.0.0\`

**Comment by Tratcher** [comment]
Option 2 seems the simplest and has the same or fewer complications than option 1. Any reason not to do that one?

**Comment by pakrym** [comment]
@Tratcher unexpected consequences of removing package from the graph that are hard to predict. I've tested options 2 with VS and it works fine. Have yet to test in Antares.

**Comment by anurse** [comment]
> No matter what we do we lose an ability to test latest HostingStartup in VS by referencing latest metapackage

If I remember correctly, the environment variables are set **before** the ones in `launchSettings.json` are applied, so in theory you could override the additional deps file when testing.

**Comment by pakrym** [comment]
@anurse, yes, I meant by default

**Comment by pakrym** [comment]
To test option 2:
1. Took `AspNetCore.All 2.0.0` package modified it to have `2.0.1` version and removed hosting startups from package references.
2. Create `dotnet new razor` app and reference `ANC.All 2.0.1`
3. Build, verified that there is no ApplicationInsights in deps file.
3. Run in VS verify that AI works - ✔️ - both `DOTNET_ADDITIONAL_DEPS` and `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` injected, data received and displayed.
4. Publish to azure app services, click AI banner, click instrument app banner, refresh the app - ✔️ - both `DOTNET_ADDITIONAL_DEPS` and `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` injected, data received and displayed.

**Comment by Eilon** [comment]
I do logically prefer option (2).

**Comment by pakrym** [comment]
I also did the same check for `Microsoft.AspNetCore.AzureAppServices.HostingStartup` and diagnostic log/log streaming works fine

**Comment by davidfowl** [comment]
I will come back to this issue when this dependency removal bites us in the ass. For now we can go with 2 😄

**Comment by glennc** [comment]
The main reason we preferred 1 was that the dependency on the SDK is marked as exlcude build, the edge for the hosting startup is not. Meaning it is demonstrably safer to remove the SDK over the hosting package.

By doing 2 we are definately removing API that could be depended upon. Removing only the SDK can only break if someone is using reflection or some other means to load an assembly that happens to be available without actually depending upon it.

**Comment by pakrym** [comment]
@glennc in option 1 API's would also go away, there would be nothing in hosting startup except `ApplicationInsightsHostingStartup` class that reflects into third assembly. So if someone happened to use `JavaScriptSnippetTagHelperComponent`, they would still get broken.

**Comment by glennc** [comment]
Then don't remove the JavascriptSnippet helper until a major version change. Just only actually load it in the other package.

It is definately easier to do 2, but it is also strictly more risky. We may be OK with that risk, but everyone should understand what we are doing. We are saying that we are OK with doing this only because of the type of code it is, and because we don't expect anyone to be using it outside of the narrow scope of lightup. Which seem like famous last words, but I can't think of any compelling scenarios right now where 2 falls apart. I just don't want everyone to think that 2 is obviously the better choice, because it isn't.

**Comment by Eilon** [comment]
Sorry I misunderstood the options. Chatted with @glennc and apparently I prefer (1).

**Comment by pakrym** [comment]
`JavaScriptSnippetTagHelperComponent` depends on AI SDK, so we would have another reflection point, and we have 3 AI SDK calls in total.

**Comment by muratg** [comment]
@davidfowl, what's your recommendation instead?  There's a clear goal stated by @glennc on the issue text -- any ideas how to achieve that without it coming back to bite us?

**Comment by davidfowl** [comment]
I prefer (1)

**Comment by pakrym** [comment]
There are couple of issues with (1):
1. While we can leave existing classes in `HostingStartup` assembly we would need to reflect into ApplicationInsights to make them functional (to get instrumentation key for `JavaScriptSnippetTagHelperComponent`). If we are doing this we would have 2 reflection calls into other assemblies and we have 3 calls to AI all together right now, so instead we can just drop reference to AI and switch all 3 calls to use reflection without adding another proxy assembly.

2. We need to generate deps files for different assembly (HostingStartup.Implementation) but ship it with an old name because of existing code in VS and Antares that adds additional deps.

**Comment by anurse** [comment]
If we're going to do (1) to avoid removing public classes, then there's no point in doing the proxy thing. `JavaScriptSnippetTagHelperComponent` is public, so we'd need to make it a proxy as well. We might as well just proxy directly to AI.

These hosting startup types should never really have been `public` in the first place, and I think it's better to fix that cleanly now, before people start depending on it (the classes are completely undocumented and are not designed for anyone to use them, and the APIs are extremely hard to discover since they're in a strange namespace) rather than have to live with that legacy. But if @pakrym and I are alone on that, then whatever, let's just make a decision and implement it.

**Comment by anurse** [comment]
It gets even scarier to keep this around when you realize we have a `public` class with a `public` constructor that references an AI type (`JavaScriptSnippet`): https://github.com/aspnet/AzureIntegration/blob/a2303c732f3dd2fd9437d9778f6d95c756fc3688/src/Microsoft.AspNetCore.ApplicationInsights.HostingStartup/JavaScriptSnippetTagHelperComponent.cs#L21

Better to make a clean cut now than try to hack stuff around.

**Comment by Eilon** [comment]
Clean cut in a patch? How do you mean?

**Comment by glennc** [comment]
The `JavaScriptSnippetTagHelperComponent` objection is reasonable though, we would need to do a bit more then just 1. Make sure that no API referenced by normal package refs gets removed.

**Comment by Eilon** [comment]
Yeah it might be extra work, but it's a patch, so if we do anything at all, we have to respect the rules of patches.

**Comment by pakrym** [comment]
We would still have to remove public constructor from public class no matter what.

**Comment by anurse** [comment]
Taking any version of this in the patch would be breaking the "rules of patches". Public APIs will need to be changed or removed.

**Comment by Eilon** [comment]
So... do we close this bug? We're not planning to do this in any patch, are we?

**Comment by pakrym** [comment]
Not in patch, possibly 2.1?

**Comment by muratg** [comment]
Putting this in 2.1.0 for now.

**Comment by pakrym** [comment]
No work here for 2.1, removing package reference would be a large breaking change.

**Comment by pakrym** [comment]
I don't think there is any work for us here as AI team now owns both site extension and hosting startup.
